config/routes.rb
Rails.application.routes.draw do

  resources :audits
  #resources :flow_condition_groups
  resources :categories do
    resources :sub_categories
  end
  get '/sub_categories', to: 'sub_categories#list'

  resources :staffs

  resources :shops do
    get 'csv_import', on: :collection
    post 'csv_import', on: :collection
    resources :staffs, controller: 'shop_staffs'
  end
  resources :flow_grants
  resources :flows do
    post 'change_default', on: :member
    resources :flow_condition_groups
  end
  resources :jobs
  resources :requests do
    get 'executable', on: :collection
    get 'flow_not_defined', on: :collection
    put 'submit', on: :member
    get 'report', on: :member
    patch 'report', on: :member
    get 'execution_report', on: :member
    patch 'execution_report', on: :member
    patch 'execution_report', on: :member
    get 'audit', on: :member
    get 'define_flow', on: :member
    put 'update_flow', on: :member
    put 'withdraw', on: :member
    put 'hide', on: :member
    resources :request_grants do
      get 'review', on: :member
    end
  end
  resources :request_audits
  resources :request_grants
  devise_for :users
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flow.rb
class Flow < ApplicationRecord
  has_many :executors, class_name: 'FlowExecutor'
  has_many :approval_flows, inverse_of: :flow
  has_one :flow_condition_group
  accepts_nested_attributes_for :approval_flows, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :executors, allow_destroy: true, reject_if: :all_blank
  scope :default, -> { where(is_default: true) }

  validates :name, presence: :true

  def copy_need_grants
    approval_flows.map do |approval_flow|
      approval_flow.request_grants.build(
        position: approval_flow.position, 
        authenticatable_type: approval_flow.authenticatable_type, 
        authenticatable_role: approval_flow.authenticatable_role, 
        authenticatable_user_id: approval_flow.authenticatable_user_id, 
        status: :not_judged
      )
    end
  end

end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController
  before_action :set_flow, only: [:show, :edit, :update, :destroy, :change_default]

  # GET /flows
  # GET /flows.json
  def index
    @flows = Flow.all
  end

  # GET /flows/1
  # GET /flows/1.json
  def show
  end

  # GET /flows/new
  def new
    @flow = Flow.new
  end

  # GET /flows/1/edit
  def edit
  end

  # POST /flows
  # POST /flows.json
  def create
    @flow = Flow.new(flow_params)

    respond_to do |format|
      if @flow.save
        format.html { redirect_to @flow, notice: '申請フロー適用条件を追加しました' }
        format.json { render :show, status: :created, location: @flow }
      else
        format.html { render :new }
        format.json { render json: @flow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flows/1
  # PATCH/PUT /flows/1.json
  def update
    respond_to do |format|
      if @flow.update(flow_params)
        format.html { redirect_to @flow, notice: 'Flow was successfully updated.' }
        format.json { render :show, status: :ok, location: @flow }
      else
        format.html { render :edit }
        format.json { render json: @flow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flows/1
  # DELETE /flows/1.json
  def destroy
    @flow.destroy
    respond_to do |format|
      format.html { redirect_to flows_url, notice: 'Flow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_default
    Flow.update_all(is_default: false)
    @flow.update_attributes(is_default: true)
    redirect_to flows_url, notice: "[#{@flow.name}]をデフォルトに設定しました"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flow
      @flow = Flow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flow_params
      params.require(:flow).permit(:name, :need_evidence, 
        approval_flows_attributes: [:id, :authenticatable_type, :authenticatable_user_id, :authenticatable_role, :position, :_destroy], 
        executors_attributes: [:id, :role, :user_id, :_destroy])
    end
end

app/views/flows/_form.html.slim
.flow-form
= simple_nested_form_for(@flow) do |f|
  = f.error_notification
  = f.input :name
  .form-group
    = f.label :need_evidence, Flow.human_attribute_name(:need_evidence), class: 'control-label'
    = f.select :need_evidence, [['あれば', false], ['必須', true]], class: 'form-control'

  h2 = ApprovalFlow.model_name.human
  .list-group.sortable
    = f.simple_fields_for :approval_flows, @flow.approval_flows.sort_by {|t| t.position } do |a|
      .list-group-item.item[data-position="#{a.object.position}"]
        .row
          .col-md-4
            = a.input :authenticatable_type, as: :select, collection: ApprovalFlow.authenticatable_type.options, input_html: {class: 'authenticatable_type'}, include_blank: false
          .col-md-6
            = a.input :authenticatable_role, as: :select, collection: User.role.options, input_html: {class: 'auth_by_role auth_pattern'}
            '
            = a.input :authenticatable_user_id, as: :select, collection: User.all.map{|t| [t.name,t.id]}, input_html: {class: 'auth_by_user auth_pattern'}
            '
            = a.input :position, as: :hidden, input_html: {class: 'approval_flow_positions'}
            '
          .col-md-2
            = a.link_to_remove do
              button.close[type="button" data-dismiss="alert" aria-label="Close"]
                span[aria-hidden="true"] = '&times;'.html_safe
    .form-inputs
      = f.link_to_add "申請ルート追加", :approval_flows, class: 'btn btn-default'

  h2 実作業者
  .list-group
    = f.simple_fields_for :executors do |executor|
      .list-group-item
        = executor.input :role, as: :select, options: User.role.options
        '
        = executor.association :user
        '
        = executor.link_to_remove do
          button.close[type="button" data-dismiss="alert" aria-label="Close"]
            span[aria-hidden="true"] = '&times;'.html_safe
    .form-inputs
      = f.link_to_add "申請ルート追加", :executors, data: {limit: 1}, class: 'btn btn-default'


  .form-actions
    = f.button :submit, t('actions.submit')
    '
    = link_to t('actions.back'), flows_path, class: 'btn btn-default'

app/views/flows/edit.html.slim
h1#flow-form Editing flow

== render 'form'

app/views/flows/index.html.slim
h1 =Flow.model_name.human + t('actions.index')
- breadcrumb :flows

table.table.table-striped.table-hover
  thead
    tr
      th = t Flow.human_attribute_name(:name)
      th Actions

  tbody
    - @flows.each do |flow|
      - class_name = flow.is_default? ? 'info' : ''
      tr[class="#{class_name}"]
        td = flow.name
        td
          = link_to t('actions.show'), flow, class: 'btn btn-default'
          = link_to t('actions.edit'), edit_flow_path(flow), class: 'btn btn-default'
          - if flow.flow_condition_group
            = link_to '適用条件編集', edit_flow_flow_condition_group_path(flow, flow.flow_condition_group), class: 'btn btn-default'
          - else
            = link_to '適用条件追加', new_flow_flow_condition_group_path(flow), class: 'btn btn-default'
          = link_to t('actions.destroy'), flow, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-default'
          - unless flow.is_default?
            = link_to 'デフォルトフローに設定', change_default_flow_path(flow), method: :post, class: 'btn btn-default'
          - else
            '
            span.label.label-info
              | デフォルト設定です

br

= link_to t('actions.create'), new_flow_path, class: 'btn btn-default'
'
= link_to t('actions.back') , root_path, class: 'btn btn-default'

app/views/flows/new.html.slim
h2 = Flow.model_name.human + t('actions.new')
== render 'form'

app/views/flows/show.html.slim
h1 =Flow.model_name.human + t('actions.show')

- breadcrumb :flow, @flow
.list-group
  a.list-group-item
    h4.list-group-item-heading
      strong = Flow.human_attribute_name(:name)
    p.list-group-item-text
      = @flow.name
    h4.list-group-item-heading
      strong = Flow.human_attribute_name(:need_evidence)
    p.list-group-item-text
      = @flow.need_evidence_text

  - if @flow.approval_flows.present?
    h2 = ApprovalFlow.model_name.human
    .list-group
      - @flow.approval_flows.order(:position).each do |approval_flow|
        .list-group-item
          span.badge[style='float: left; margin-right: 10px;']
            = approval_flow.position
          '
          = approval_flow.authenticatable_role_text || approval_flow.authenticatable_user.try(:name)
  - if @flow.executors.present?
    h2 = FlowExecutor.model_name.human
    .list-group
      - @flow.executors.each do |executor|
        .list-group-item
          - if executor.role
            = executor.role_text
            '
          - if executor.user
            = executor.user.name
 
= link_to t('actions.edit'), edit_flow_path(@flow), class: 'btn btn-default'
'
= link_to t('actions.back'), flows_path, class: 'btn btn-default'