config/routes.rb
Rails.application.routes.draw do

  resources :audits
  #resources :flow_condition_groups
  resources :categories do
    resources :sub_categories
  end
  get '/sub_categories', to: 'sub_categories#list'

  resources :staffs

  resources :shops do
    get 'csv_import', on: :collection
    post 'csv_import', on: :collection
    resources :staffs, controller: 'shop_staffs'
  end
  resources :flow_grants
  resources :flows do
    post 'change_default', on: :member
    resources :flow_condition_groups
  end
  resources :jobs
  resources :requests do
    get 'executable', on: :collection
    get 'flow_not_defined', on: :collection
    put 'submit', on: :member
    get 'report', on: :member
    patch 'report', on: :member
    get 'execution_report', on: :member
    patch 'execution_report', on: :member
    patch 'execution_report', on: :member
    get 'audit', on: :member
    get 'define_flow', on: :member
    put 'update_flow', on: :member
    put 'withdraw', on: :member
    put 'hide', on: :member
    resources :request_grants do
      get 'review', on: :member
    end
  end
  resources :request_audits
  resources :request_grants
  devise_for :users
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  extend Enumerize
  belongs_to :flow
  belongs_to :user
  belongs_to :client_user, class_name: 'User'
  belongs_to :category
  belongs_to :sub_category
  has_many :request_grants
  has_many :costs, class_name: 'RequestCost'

  has_many :initial_human_cost, class_name: 'RequestInitialHumanCost'
  has_many :monthly_human_cost, class_name: 'RequestMonthlyHumanCost'
  has_many :annual_human_cost,  class_name: 'RequestAnnualHumanCost'
  has_one :initial_money_cost, class_name: 'RequestInitialMoneyCost'
  has_many :monthly_money_cost, class_name: 'RequestMonthlyMoneyCost'
  has_many :annual_money_cost,  class_name: 'RequestAnnualMoneyCost'
  has_one :money_cost,  class_name: 'RequestMoneyCost'

  audited associated_with: :category
  has_associated_audits

  has_many :execution_evidences
  has_many :finishing_evidences
  #scope :reviewable, ->(user) { joins(:request_grants).merge(RequestGrant.user_reviewable(user)) }
  scope :executable, ->(user) { where(status: :wait_for_execution).joins(flow: :executors).merge(FlowExecutor.by_user(user)) }
  scope :displayable_status, ->(displayable) { where(displayable: displayable) }
  scope :by_user, ->(user) { where(user: user) }
  enumerize :status, in: [:not_submitted, :flow_not_defined, :reviewing, :rejected, :executable, :executed, :finished, :wait_for_execution], scope: true
  accepts_nested_attributes_for :finishing_evidences, allow_destroy: true
  accepts_nested_attributes_for :execution_evidences, allow_destroy: true
  accepts_nested_attributes_for :costs, allow_destroy: true

  accepts_nested_attributes_for :initial_human_cost, allow_destroy: true
  accepts_nested_attributes_for :monthly_human_cost, allow_destroy: true
  accepts_nested_attributes_for :annual_human_cost,  allow_destroy: true
  accepts_nested_attributes_for :initial_money_cost, allow_destroy: true
  accepts_nested_attributes_for :monthly_money_cost, allow_destroy: true
  accepts_nested_attributes_for :annual_money_cost,  allow_destroy: true
  accepts_nested_attributes_for :money_cost,  allow_destroy: true, reject_if: :all_blank

  validates :title, presence: :true

  attr_accessor :has_client

  def unsaved_initial_costs
    initial_human_cost.select{|t| t if  t.new_record? }
  end

  def associated_value(name)
    Rails.logger.debug name
    case 
    when name.in?(%i(initial_money_cost initial_human_cost monthly_human_cost annual_human_cost monthly_money_cost annual_money_cost money_cost)) then
      self.__send__(name).try(:cost_value).to_i
    when name.in?(%i(price)) then
      total_money_cost
    end
  end

  def next_request_grant
    request_grants.with_status(:not_judged).order(:position).first
  end

  def current_request_grant
    request_grants.with_status(:reviewing).order(:position).first
  end

  private
    def total_money_cost
      initial_money_cost.try(:cost_value).to_i + monthly_money_cost.try(:cost_value).to_i + annual_money_cost.try(:cost_value).to_i
    end


end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
  def index
    with_undisplayable = params[:with_undisplayable]
    @requests = RequestFlowPolicy.accessible_requests(current_user, :show, options={with_undisplayable: with_undisplayable})
  end

  def audit
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :show, options={with_undisplayable: true})
    @audits = @request.audits.order(:created_at)
  end

  def executable
    @requests = RequestFlowPolicy.accessible_requests(current_user, :execute)
  end

  def flow_not_defined
    @requests = RequestFlowPolicy.accessible_requests(current_user, :define_flow)
  end

  def edit
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :edit)
  end

  def define_flow
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :define_flow)
  end

  def update_flow
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :define_flow)
    @request.assign_attributes(define_flow_params)
    if RequestFlowPolicy.new(request: @request).save_request_and_select_flow
      redirect_to @request, notice: 'Request was successfully updated.'
    else
      render :edit
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :show)
  end

  def hide
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :hide)
    RequestFlowPolicy.new(request: @request).hide!(current_user)
    redirect_to requests_path, notice: '非表示にしました'
  end

  def withdraw
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :withdraw)
    RequestFlowPolicy.new(request: @request).withdraw!(current_user)
    redirect_to requests_path, notice: '申請を取り消しました'
  end

  def submit
    if RequestFlowPolicy.accesible_request?(@request, current_user, :submit)
      RequestFlowPolicy.new(request: @request).save_request_and_select_flow
      redirect_to requests_path, notice: '申請を提出しました'
    else
      raise StandardError
    end
  end


  # GET /requests/new
  def new
    @request = Request.new
    @request.has_client = params[:has_client]
  end

  def execution_report
    @request  = RequestFlowPolicy.accessible_request(params[:id], current_user, :execute)
    if request.patch?
      @request.assign_attributes(request_params) if params[:request].present?
      if RequestFlowPolicy.new(request: @request).executed!(current_user.id)
        redirect_to @request, notice: '申請者に通知しました'
      else
        render :report
      end
    end
  end

  def report
    if request.patch?
      @request.assign_attributes(request_params)
      if RequestFlowPolicy.new(request: @request).finish!
        redirect_to @request, notice: '管理部に通知しました'
      else
        render :report
      end
    end
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    authorize! :create, @request
    if RequestFlowPolicy.new(request: @request).save_request_and_select_flow
      redirect_to requests_path, notice: '申請が完了しました'
    else
      render :new
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :edit)
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = RequestFlowPolicy.accessible_request(params[:id], current_user, :destroy)
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:id, :flow_id, :user_id, :category_id, :sub_category_id, :title, :description,
        :client_user_id,
        money_cost_attributes: [
          :id,
          :request_id,
          :_destroy,
          :cost_value,
          :annotation,
        ], 
        costs_attributes: [
          :_destroy,
          :initial_cost,
          :price,
          :time_required,
          :person_number, 
          :cost_price_type
        ], 
        initial_money_cost_attributes: [
          :id,
          :request_id,
          :_destroy,
          :cost_value,
          :annotation,
        ], 
        monthly_money_cost_attributes: [
          :id,
          :_destroy,
          :cost_value,
          :annotation,
        ], 
        annual_money_cost_attributes: [
          :id,
          :_destroy,
          :cost_value,
          :annotation,
        ], 
        initial_human_cost_attributes: [
          :id,
          :_destroy,
          :time_required,
          :number_of_people,
          :annotation,
        ], 
        monthly_human_cost_attributes: [
          :id,
          :_destroy,
          :time_required,
          :number_of_people,
          :annotation,
        ], 
        annual_human_cost_attributes: [
          :id,
          :_destroy,
          :time_required,
          :number_of_people,
          :annotation,
        ], 
        finishing_evidences_attributes: [
          :_destroy,
          :id,
          :comment,
          :file_name,
          :remove_file_name,
        ],
        execution_evidences_attributes: [
          :_destroy,
          :id,
          :comment,
          :file_name,
          :remove_file_name,
        ],
      )
    end

    def define_flow_params
      params.require(:request).permit(:flow_id)
    end

end

app/views/requests/_form.html.slim
.request-form
= simple_nested_form_for(@request) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
    - if @request.has_client
    = f.input  :client_user_id,  as: :select, collection: User.all.map{|t| [t.name, t.id] }
    = f.input :title
    = f.input :description
    = f.association :category
    = f.association :sub_category
  = f.simple_fields_for :money_cost do |c|
    .panel.panel-default
      .panel-body
        legend = RequestMoneyCost.model_name.human
        p
          .input-group
            = c.input  :id, as: :hidden
            = c.input  :request_id, as: :hidden
            = c.input :cost_value
        p
          .input-group
            = c.input :annotation
        br
        = c.link_to_remove "削除", class: 'btn btn-warning'
  = f.link_to_add RequestMoneyCost.model_name.human + t('actions.add'), :money_cost, class: 'btn btn-primary', data: {limit: 1}
  br
  br

  .form-actions
    = f.button :submit, t('actions.submit'), class: 'btn btn-default'
    = link_to t('actions.back'), requests_path, class: 'btn btn-default'

app/views/requests/_list.html.slim
table.table.table-striped.table-hover
  thead
    tr
      th Id
      th Title
      th = t Request.human_attribute_name(:user)
      th 申請フロー
      th = t Request.human_attribute_name(:status)
      th Action

  tbody
    - @requests.each do |request|
      - tr_class = request.status_color
      tr[class="#{tr_class}"]
        td = request.id
        td = request.title
        td = request.user.name
        td = request.flow.try(:name)
        td = request.status_message
        td 
          = link_to '詳細', request, class: 'btn btn-default'
          '
          = link_to 'log', audit_request_path(request), class: 'btn btn-default'
          '
          - if RequestFlowPolicy.accesible_request?(request, current_user, :withdraw)
            '
            = link_to '申請を取り消す', withdraw_request_path(request), 
              data: { confirm: '申請を取り消すと今までの承認がリセットされますがよろしいですか?' },
              method: :put, class: 'btn btn-danger'
            '
          - if request.status == 'executed'
            = link_to '作業完了報告', report_request_path(request), class: 'btn btn-default'
            '
          - if RequestFlowPolicy.accesible_request?(request, current_user, :edit)
            = link_to '編集', edit_request_path(request), class: 'btn btn-default'
            '
          - if RequestFlowPolicy.accesible_request?(request, current_user, :submit)
            = link_to '提出', submit_request_path(request), class: 'btn btn-default', method: :put
            '
          = link_to '非表示', hide_request_path(request), class: 'btn btn-default', method: :put
          '
          - if RequestFlowPolicy.accesible_request?(request, current_user, :define_flow)
            = link_to '申請フローを選択する', define_flow_request_path(request), class: 'btn btn-default'
          - if RequestFlowPolicy.accesible_request?(request, current_user, :delete)
            = link_to t('actions.destroy'), request, data: { confirm: '削除してもよろしいですか?' }, method: :delete, class: 'btn btn-default'

app/views/requests/audit.html.slim
h1 =Request.model_name.human + t('actions.index')
- breadcrumb :request_audit, @request
br



table.table.table-hover
  thead
    tr
      th Type
      th When
      th Who
      th What Changed
    - @audits.order(:created_at).each do |audit|
      tr
        td= audit.action
        td= audit.created_at
        td= audit.try(:user).try(:name)
        td
          - AuditDecorator.new(object: audit).audited_changes.each_with_index do |v,k|
            - if v.info_exists?
              b= v.subject_column_name
              br
              - if v.update_info?
                - if v.info_with_enumerize?
                  - ret = v.associated_before_after
                  b= ret.first || '未設定'
                  '
                  i.fa.fa-arrow-right.fa-lg
                  '
                  b= ret.last || '未設定'
                  br
                - else
                  b= v.before
                  '
                  i.fa.fa-arrow-right.fa-lg
                  '
                  b= v.after
                  br
              - else
                b= v.first_value_for_created_record
                br
= link_to 'Back', requests_path, class: 'btn btn-default'

app/views/requests/define_flow.html.slim
h1 =Request.model_name.human
span.help-block この申請は承認フローが選択されていません。承認フローを選択または作成してください

.list-group
  a.list-group-item
    h4.list-group-item-heading
      = Request.human_attribute_name(:user)
    p.list-group-item-text
      = @request.user.name
    - if @request.client_user
      h4.list-group-item-heading
        = Request.human_attribute_name(:client_user)
      p.list-group-item-text
        = @request.client_user.name
    h4.list-group-item-heading
      = Request.human_attribute_name(:title)
    p.list-group-item-text
      = @request.title
    h4.list-group-item-heading
      = Request.human_attribute_name(:description)
    p.list-group-item-text
      = @request.description

= simple_form_for(@request, url: update_flow_request_path(@request), method: :put) do |f|
  = f.error_notification

  .form-inputs
    = f.association :flow
    = link_to '新規flowを登録', new_flow_path

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

= link_to 'Back', requests_path

app/views/requests/edit.html.slim
h1 = Request.model_name.human

== render 'form'

app/views/requests/executable.html.slim
h2 (承認済み)物品購入依頼,作業依頼一覧

table.table.table-striped.table-hover
  thead
    tr
      th Id
      th Title
      th = t Request.human_attribute_name(:user)
      th 申請フロー
      th = t Request.human_attribute_name(:status)
      th Action
  tbody
    - @requests.each do |request|
      tr
        td = request.id
        td = request.title
        td = request.user.name
        td = request.flow.try(:name)
        td = request.status_message
        td 
          '
          - if request.status == 'wait_for_execution'
            = link_to '購入/実行完了報告', execution_report_request_path(request), class: 'btn btn-default'

br

app/views/requests/execution_report.html.slim
h2 (承認済み)物品購入依頼,作業依頼に対する購入/作業報告
span.help-block 以下の内容について物品購入などの作業が完了していれば送信ボタンを押してステータスを終了に更新できます
span.help-block 必要に応じて資料を添付してください

.list-group
  a.list-group-item
    h4.list-group-item-heading
      | User
    p.list-group-item-text
      = @request.user.name
    h4.list-group-item-heading
      | Title
    p.list-group-item-text
      = @request.title
    h4.list-group-item-heading
      | Description:
    p.list-group-item-text
      = @request.description

- if @request.request_grants.present?
  h2 承認状況
  .list-group
    - @request.request_grants.order(:position).each do |request_grant|
      - request_grant = ActiveDecorator::Decorator.instance.decorate(request_grant)
      .list-group-item
        = request_grant.position
        '
        = request_grant.authenticatable_role_text
        '
        = request_grant.authenticated_user.try(:name)
        '
        span[class="#{request_grant.status_label_class}"]
          = request_grant.status_text

= simple_nested_form_for(@request, url: execution_report_request_path(@request)) do |f|
  = f.simple_fields_for :execution_evidences do |e_f|
    .panel.panel-default
      .panel-body
        p
          label = Evidence.human_attribute_name(:file_name)
          .input-group
            = image_tag e_f.object.file_name.thumb if e_f.object.file_name?
            = e_f.file_field :file_name
        p
          label = Evidence.human_attribute_name(:comment)
            = e_f.check_box :remove_file_name
            | 画像削除
        = e_f.text_area :comment, class: 'form-control'
        br
        = e_f.link_to_remove "削除", class: 'btn btn-warning'
  '
  = f.link_to_add "資料追加", :execution_evidences, class: 'btn btn-default'
  br
  br
  .form-actions
    = f.button :submit, class: 'btn btn-default', value: '作業完了', data: { confirm: 'この申請を作業完了/購入済みにしてよろしいですか?' }
    '
    = link_to t('actions.back'), requests_path, class: 'btn btn-default'

app/views/requests/flow_not_defined.html.slim
h2 承認フロー未設定申請一覧

= render 'list'
br

app/views/requests/index.html.slim
h1 =Request.model_name.human + t('actions.index')
- breadcrumb :requests
= render 'list'
br

= link_to '新規申請を出す', new_request_path, class: 'btn btn-default'
'
= link_to '代理申請を出す', new_request_path(has_client: true), class: 'btn btn-default'
'
= link_to '完了した申請を表示', requests_path(with_undisplayable: true), class: 'btn btn-default'

app/views/requests/new.html.slim
h1 =Request.model_name.human

== render 'form'

app/views/requests/report.html.slim
h2 完了報告
span.help-block 以下の内容について作業が完了していれば送信ボタンを押してステータスを終了に更新できます
span.help-block 必要に応じて証明資料を添付してください

.list-group
  a.list-group-item
    h4.list-group-item-heading
      | User
    p.list-group-item-text
      = @request.user.name
    - if @request.client_user
      h4.list-group-item-heading
        | 申請依頼者
      p.list-group-item-text
        = @request.client_user.name
    h4.list-group-item-heading
      | Title
    p.list-group-item-text
      = @request.title
    h4.list-group-item-heading
      | Description:
    p.list-group-item-text
      = @request.description

- if @request.execution_evidences.present?
  h3 購入者(作業者)資料
  .list-group
    - @request.execution_evidences.each do |execution_evidence|
      a.list-group-item
        h4.list-group-item-heading
          | 画像
        p.list-group-item-text
          = image_tag execution_evidence.file_name
        h4.list-group-item-heading
          | コメント
        p.list-group-item-text
          = execution_evidence.comment
        h4.list-group-item-heading
          | 作業者
        p.list-group-item-text
          = execution_evidence.upload_user.try(:name)
 


= simple_nested_form_for(@request, url: report_request_path(@request)  ) do |f|
  = f.simple_fields_for :finishing_evidences do |e_f|
    .panel.panel-default
      .panel-body
        p
          label = Evidence.human_attribute_name(:file_name)
          .input-group
            = image_tag e_f.object.file_name.thumb if e_f.object.file_name?
            = e_f.file_field :file_name
        p
          label = Evidence.human_attribute_name(:comment)
            = e_f.check_box :remove_file_name
            | 画像削除
        = e_f.text_area :comment, class: 'form-control'
        br
        = e_f.link_to_remove "削除", class: 'btn btn-warning'
  '
  = f.link_to_add "資料追加", :finishing_evidences, class: 'btn btn-primary'
  br
  br
  .form-actions
    = f.button :submit, class: 'btn btn-primary', value: '送信'

br
= link_to 'Back', requests_path, class: 'btn btn-primary'

app/views/requests/show.html.slim
- breadcrumb :request, @request
.list-group
  a.list-group-item
    - if @request.flow
      h4.list-group-item-heading
        strong = Request.human_attribute_name(:flow)
      p.list-group-item-text
        = @request.flow.try(:title)
    - if @request.category
      h4.list-group-item-heading
        strong = Request.human_attribute_name(:category)
      p.list-group-item-text
        = @request.category.try(:name)
    - if @request.sub_category
      h4.list-group-item-heading
        strong = Request.human_attribute_name(:subcategory)
      p.list-group-item-text
        = @request.sub_category.try(:name)
    h4.list-group-item-heading
      strong = Request.human_attribute_name(:user)
    p.list-group-item-text
      = @request.user.name
    - if @request.client_user
      h4.list-group-item-heading
        strong = Request.human_attribute_name(:client_user)
      p.list-group-item-text
        = @request.client_user.name
    h4.list-group-item-heading
      strong = Request.human_attribute_name(:title)
    p.list-group-item-text
      = @request.title
    h4.list-group-item-heading
      strong = Request.human_attribute_name(:description)
    p.list-group-item-text
      = @request.description

  - if @request.costs.present?
    h2 = RequestCost.model_name.human
    .list-group
      - @request.costs.each do |cost|
        a.list-group-item
          h4.list-group-item-heading
            strong = RequestCost.human_attribute_name(:cost_price_type)
          p.list-group-item-text
            = cost.cost_price_type_text
          h4.list-group-item-heading
            strong = RequestCost.human_attribute_name(:initial_cost)
          p.list-group-item-text
            = cost.initial_cost
          h4.list-group-item-heading
            strong = RequestCost.human_attribute_name(:price)
          p.list-group-item-text
            = cost.price
          h4.list-group-item-heading
            strong = RequestCost.human_attribute_name(:time_required)
          p.list-group-item-text
            = cost.time_required
          h4.list-group-item-heading
            strong = RequestCost.human_attribute_name(:person_number)
          p.list-group-item-text
            = cost.person_number

  - if @request.request_grants.present?
    h2 承認状況
    .list-group
      - @request.request_grants.order(:position).each do |request_grant|
        - request_grant = ActiveDecorator::Decorator.instance.decorate(request_grant)
        .list-group-item
          = request_grant.position
          '
          = request_grant.authenticatable_role_text || request_grant.authenticatable_user.try(:name)
          '
          = request_grant.authenticated_user.try(:name)
          '
          span[class="#{request_grant.status_label_class}"]
            = request_grant.status_text
          - if request_grant.comment
            br
            | comment:
            '
            = request_grant.comment



- if @request.execution_evidences.present?
  h3 購入者(作業者)資料
  .list-group
    - @request.execution_evidences.each do |execution_evidence|
      a.list-group-item
        h4.list-group-item-heading
          | 画像
        p.list-group-item-text
          = image_tag execution_evidence.file_name
        h4.list-group-item-heading
          | コメント
        p.list-group-item-text
          = execution_evidence.comment
        h4.list-group-item-heading
          | 作業者
        p.list-group-item-text
          = execution_evidence.upload_user.try(:name)

- if @request.finishing_evidences.present?
  h3 申請者提出資料
  .list-group
    - @request.finishing_evidences.each do |finishing_evidence|
      a.list-group-item
        h4.list-group-item-heading
          | 画像
        p.list-group-item-text
          = image_tag finishing_evidence.file_name
        h4.list-group-item-heading
          | コメント
        p.list-group-item-text
          = finishing_evidence.comment
        h4.list-group-item-heading
          | 作業者
        p.list-group-item-text
          = finishing_evidence.upload_user.try(:name)
 

= link_to 'Back', requests_path, class: 'btn btn-default'