config/routes.rb
Rails.application.routes.draw do

  resources :audits
  #resources :flow_condition_groups
  resources :categories do
    resources :sub_categories
  end
  get '/sub_categories', to: 'sub_categories#list'

  resources :staffs

  resources :shops do
    get 'csv_import', on: :collection
    post 'csv_import', on: :collection
    resources :staffs, controller: 'shop_staffs'
  end
  resources :flow_grants
  resources :flows do
    post 'change_default', on: :member
    resources :flow_condition_groups
  end
  resources :jobs
  resources :requests do
    get 'executable', on: :collection
    get 'flow_not_defined', on: :collection
    put 'submit', on: :member
    get 'report', on: :member
    patch 'report', on: :member
    get 'execution_report', on: :member
    patch 'execution_report', on: :member
    patch 'execution_report', on: :member
    get 'audit', on: :member
    get 'define_flow', on: :member
    put 'update_flow', on: :member
    put 'withdraw', on: :member
    put 'hide', on: :member
    resources :request_grants do
      get 'review', on: :member
    end
  end
  resources :request_audits
  resources :request_grants
  devise_for :users
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  has_many :requests
  belongs_to :category
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_category, except: [:list]
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = @category.sub_categories
    respond_to do |format|
      format.json { @sub_categories.map {|t| [t.id,t.name] } }
      format.html
    end
  end

  def list
    render json: @categories = SubCategory.joins(:category).merge(Category.where(id: params[:category_ids])).map {|t| [t.id,t.name] }
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:category_id])
    end

    def set_sub_category
      @sub_category = @category.sub_category.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:category_id, :name)
    end
end

app/views/sub_categories/_form.html.slim
= simple_form_for(@sub_category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :category_id
    = f.input :name

  .form-actions
    = f.button :submit

app/views/sub_categories/edit.html.slim
h1 Editing sub_category

== render 'form'

= link_to 'Show', @sub_category
'|
= link_to 'Back', sub_categories_path

app/views/sub_categories/index.html.slim
h2 = @category.name + 'の' + SubCategory.model_name.human + t('actions.index')
- breadcrumb :sub_categories

table.table.table-striped.table-hover
  thead
    tr
      th Name
      th Actions

  tbody
    - @sub_categories.each do |sub_category|
      tr
        td = sub_category.name
        td = link_to t('actions.show'), category_sub_category_path(@category, sub_category), class: 'btn btn-default'
        td = link_to t('actions.edit'), edit_category_sub_category_path(@category, sub_category), class: 'btn btn-default'
        td = link_to t('actions.destroy'), category_sub_category_path(@category, sub_category), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-default'

br

= link_to t('actions.new'), new_category_sub_category_path(@category), class: 'btn btn-default'

app/views/sub_categories/new.html.slim
h1 New sub_category

== render 'form'

= link_to 'Back', sub_categories_path

app/views/sub_categories/show.html.slim
- breadcrumb :categories

p
  strong Category:
  = @sub_category.category_id
p
  strong Name:
  = @sub_category.name

= link_to 'Edit', edit_sub_category_path(@sub_category)
'|
= link_to 'Back', sub_categories_path