config/routes.rb
Rails.application.routes.draw do

  resources :audits
  #resources :flow_condition_groups
  resources :categories do
    resources :sub_categories
  end
  get '/sub_categories', to: 'sub_categories#list'

  resources :staffs

  resources :shops do
    get 'csv_import', on: :collection
    post 'csv_import', on: :collection
    resources :staffs, controller: 'shop_staffs'
  end
  resources :flow_grants
  resources :flows do
    post 'change_default', on: :member
    resources :flow_condition_groups
  end
  resources :jobs
  resources :requests do
    get 'executable', on: :collection
    get 'flow_not_defined', on: :collection
    put 'submit', on: :member
    get 'report', on: :member
    patch 'report', on: :member
    get 'execution_report', on: :member
    patch 'execution_report', on: :member
    patch 'execution_report', on: :member
    get 'audit', on: :member
    get 'define_flow', on: :member
    put 'update_flow', on: :member
    put 'withdraw', on: :member
    put 'hide', on: :member
    resources :request_grants do
      get 'review', on: :member
    end
  end
  resources :request_audits
  resources :request_grants
  devise_for :users
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :requests
  has_many :sub_categories
  has_associated_audits
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource



  # GET /categories
  # GET /categories.json
  def index
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @categories.map {|t| [t.id,t.name] } }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 =Category.model_name.human + t('actions.index')
- breadcrumb :categories

table.table.table-striped.table-hover
  thead
    tr
      th Name
      th Actions

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td
          = link_to 'Show', category, class: 'btn btn-default'
          '
          = link_to SubCategory.model_name.human + t('actions.index'), category_sub_categories_path(category), class: 'btn btn-default'
          '
          - if can? :manage, category
            = link_to 'Edit', edit_category_path(category), class: 'btn btn-default'
            '
          - if can? :destroy, category
            = link_to 'Destroy', category, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-default'

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path